// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func Oauth2BasicResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"attrs": schema.MapAttribute{
				ElementType: types.ListType{
					ElemType: types.StringType,
				},
				Required: true,
			},
			"rs_name": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

type Oauth2BasicModel struct {
	Attrs  types.Map    `tfsdk:"attrs"`
	RsName types.String `tfsdk:"rs_name"`
}
