// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ServiceAccountResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"attrs": schema.MapAttribute{
				ElementType: types.ListType{
					ElemType: types.StringType,
				},
				Required: true,
			},
			"id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

type ServiceAccountModel struct {
	Attrs types.Map    `tfsdk:"attrs"`
	Id    types.String `tfsdk:"id"`
}
